plugins {
    id 'net.fabricmc.fabric-loom' version '1.16.2'
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = project.archives_base_name
}

loom {
    accessWidenerPath = file("src/main/resources/beaconoverhaul.accesswidener")
}


repositories {
    maven {
        name = "Jamies White Shirt"
        url = "https://maven.jamieswhiteshirt.com/libs-release"
    }
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/releases"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    // Mappings are not needed for unobfuscated Minecraft 26.1.2




    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    // Checker Framework & Jetbrains Annotations
    implementation "org.jetbrains:annotations:24.0.1"
    implementation "org.checkerframework:checker-qual:3.35.0"
}

processResources {
    inputs.property "version", project.version

    filesMatching("fabric.mod.json") {
        expand "version": project.version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 26
    it.options.encoding = "UTF-8"
}


java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_26
    targetCompatibility = JavaVersion.VERSION_26
}

jar {
    from("LICENSE") {
        rename { "${it}_${project.base.archivesName.get()}"}
    }
}
